#!/bin/sh 
# Rational Vault Client
#
### BEGIN INIT INFO
# Provides: Metadata Syncer from Neridio System
# Required-Start: 45
# Default-Stop: 0 1 2 3 6
# description: Rational Vault Client
### END INIT INFO 
. /etc/init.d/functions
prog=rclient
DEVICE=`/sbin/ip link | grep "BROADCAST,MULTICAST,UP,LOWER_UP" | head -1 | cut -d " " -f2 | cut -d ":" -f1 `
export IP=`/sbin/ifconfig "$DEVICE" |grep -w "inet"|gawk '{print $2}'|gawk '{print $1}'`
start() {
	# Start daemons.
	echo -n $"Starting $prog: "
	/rationalVault/bin/${prog} 
	RETVAL=$?
        echo
	return $RETVAL
}

stop() {
    [ "$EUID" != "0" ] && exit 4
    echo -n $"Shutting down $prog: "
    killproc $prog >/dev/null 2>&1
    pkill -9 -f /rationalVault/bin/$prog >/dev/null 2>&1
    RETVAL=$?
        echo
    return $RETVAL
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  status)
    status $prog
    ;;
  restart|force-reload)
    stop
    start
    ;;
  try-restart|condrestart)
    if status $prog > /dev/null; then
        stop
        start
    fi
    ;;
  reload)
    exit 3
    ;;
  *)
    echo $"Usage: $0 {start|stop|status|restart|try-restart|force-reload}"
    exit 2
esac
